#define LINEAR_LATTICE_DIMENSION_MIN			10
#define LINEAR_LATTICE_DIMENSION_MAX			25
#define LINEAR_LATTICE_DIMENSION_INIT		    20
#define DELTA_MIN	0
#define DELTA_MAX	1000
#define DELTA_INIT	0
#define POS_TRAITS_MIN		1
#define POS_TRAITS_MAX		100
#define POS_TRAITS_INIT		5
#define SIM_SPEED_MIN		0.001
#define SIM_SPEED_MAX		1
#define SIM_SPEED_INIT		0.32 

/* Interface Dimensions */
#define WINDOW_WIDTH 950
#define WINDOW_HIGH 730
#define SIMULATION_WIDTH 690
#define SIMULATION_HIGH 690
#define STATS_W 312
#define STATS_H 625
#define STATS2_W 312
#define STATS2_H 625


#define AGENTS LINEAR_LATTICE_DIMENSION_INIT*LINEAR_LATTICE_DIMENSION_INIT
#define NFEATURES 3
#define POS_FEATURES 10
#define N_ITER 10
#define OUTDEGREE 4
