// generated by Fast Light User Interface Designer (fluid) version 1.0109

#include "elanja-fltk.h"
#include "gui_controls.h"
#include "widgetWindow.h"

static simulationGrid glf(10,30,745,500); 

/************* Main Window *****************************************/
Fl_Double_Window *elanjaWindow=(Fl_Double_Window *)0;
/************* Play/Stop Buttons ***********************************/
Fl_Button *playButton=(Fl_Button *)0;

Fl_Button *stopButton=(Fl_Button *)0;
/************* Simulation Steps ************************************/
Fl_Value_Output *simStepLabel=(Fl_Value_Output *)0;
/************* Slider's Group **************************************/
Fl_Group *parametersGroup=(Fl_Group *)0;

Fl_Value_Slider *agentsSlider=(Fl_Value_Slider *)0;

Fl_Value_Slider *populationSlider=(Fl_Value_Slider *)0;

Fl_Value_Slider *epsilonSlider=(Fl_Value_Slider *)0;

Fl_Value_Slider *friendshipSlider=(Fl_Value_Slider *)0;

Fl_Value_Slider *numProductsSlider=(Fl_Value_Slider *)0;

Fl_Value_Slider *simSpeedSlider=(Fl_Value_Slider *)0;
/************* Check Buttons ***************************************/
Fl_Check_Button *perturbationButton=(Fl_Check_Button *)0;

Fl_Check_Button *hubsButton=(Fl_Check_Button *)0;
/************* Menu ************************************************/
Fl_Menu_Item menu_Visualizza[] = {
 {"File", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Exit", 0,  (Fl_Callback*)exitCallback, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Simulation", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"@> Play", 0,  (Fl_Callback*)playCallback, (void*)(&glf), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"@|> Restart", 0,  (Fl_Callback*)stopCallback, (void*)(&glf), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"View", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

int main(int argc, char **argv) 
{
	glf.mode(FL_DOUBLE);
	{	/* Main Window */
	 	elanjaWindow = new Fl_Double_Window(765, 730, "Elanja");
		elanjaWindow->color(FL_LIGHT3);
		elanjaWindow->selection_color((Fl_Color)53);
    		{	/* Button's Group */ 
			Fl_Group* o = new Fl_Group(585, 660, 172, 65);
			{ 	/* Play Button */
				playButton = new Fl_Button(675, 695, 70, 30, "@>");
        			playButton->callback((Fl_Callback*)playCallback, (void*)(&glf));
      			} 
      			{	/* Stop Button */
				stopButton = new Fl_Button(595, 695, 70, 30, "@|>");
        			stopButton->callback((Fl_Callback*)stopCallback, (void*)(&glf));
	      		} 
      			{	/* Simulation Steps */
				simStepLabel = new Fl_Value_Output(585, 660, 172, 25, "Simulation step:");
        			simStepLabel->maximum(1e+06);
        			simStepLabel->align(FL_ALIGN_TOP_LEFT);
      			} 
      			o->end();
    		} 
		{	/* Parameters Group */
			parametersGroup = new Fl_Group(10, 535, 560, 190, "Parameters");
      			parametersGroup->box(FL_PLASTIC_UP_FRAME);
      			parametersGroup->color(FL_FOREGROUND_COLOR);
      			parametersGroup->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
			{ 	/* Agent Slider */
				agentsSlider = new Fl_Value_Slider(15, 570, 240, 35, "Agents");
        			agentsSlider->type(5);
        			//agentsSlider->box(FL_THIN_DOWN_BOX);/* Borders dimension */
        			agentsSlider->color((Fl_Color)124);/* Slider color */
        			agentsSlider->selection_color((Fl_Color)136);/* Cursor color */
        			agentsSlider->labelfont(1);
        			agentsSlider->labelsize(12);
				agentsSlider->minimum(1);
        			agentsSlider->maximum(100);
        			agentsSlider->step(2);
        			agentsSlider->value(10);
        			agentsSlider->callback((Fl_Callback*)agentsSliderCallback);
        			agentsSlider->align(FL_ALIGN_TOP_LEFT);/* Label align*/
      			}
      			{ 	/* Population Slider */
				populationSlider = new Fl_Value_Slider(15, 625, 240, 35, "Population");
        			populationSlider->type(5);
        			//populationSlider->box(FL_THIN_DOWN_BOX);
        			populationSlider->color((Fl_Color)124);
        			populationSlider->selection_color((Fl_Color)136);
				populationSlider->minimum(10);
        			populationSlider->maximum(100);
        			populationSlider->labelfont(1);
        			populationSlider->labelsize(12);
        			populationSlider->value(50);
				populationSlider->step(10);
        			populationSlider->callback((Fl_Callback*)populationSliderCallback);
        			populationSlider->align(FL_ALIGN_TOP_LEFT);
      			}
      			{	/* Epsilon Slider */
		 		epsilonSlider = new Fl_Value_Slider(290, 570, 260, 35, "Epsilon");
        			epsilonSlider->type(5);
        			//epsilonSlider->box(FL_THIN_DOWN_BOX);
        			epsilonSlider->color((Fl_Color)124);
        			epsilonSlider->selection_color((Fl_Color)136);
        			epsilonSlider->labelfont(1);
        			epsilonSlider->labelsize(12);
        			epsilonSlider->minimum(1);
        			epsilonSlider->maximum(10);
        			epsilonSlider->step(0.1);
        			epsilonSlider->value(5);
        			epsilonSlider->callback((Fl_Callback*)epsilonSliderCallback);
        			epsilonSlider->align(FL_ALIGN_TOP_LEFT);
      			}
      			{	/* Friendship Slider */
				friendshipSlider = new Fl_Value_Slider(290, 625, 260, 35, "Frienship");
        			friendshipSlider->type(5);
			        friendshipSlider->box(FL_THIN_DOWN_BOX);
			        friendshipSlider->color((Fl_Color)124);
			        friendshipSlider->selection_color((Fl_Color)136);
			        friendshipSlider->labelfont(1);
			        friendshipSlider->labelsize(12);
        			friendshipSlider->minimum(1);
			        friendshipSlider->maximum(100);
			        friendshipSlider->step(1);
			        friendshipSlider->value(10);
			        friendshipSlider->callback((Fl_Callback*)friendshipSliderCallback);
			        friendshipSlider->align(FL_ALIGN_TOP_LEFT);
			}
      			{	/* Simulation Speed Slider */
				simSpeedSlider = new Fl_Value_Slider(160, 685, 240, 35, "Simulation Speed");
        			simSpeedSlider->type(5);
			        simSpeedSlider->box(FL_THIN_DOWN_BOX);
			        simSpeedSlider->color((Fl_Color)124);
			        simSpeedSlider->selection_color((Fl_Color)136);
			        simSpeedSlider->labelfont(1);
			        simSpeedSlider->labelsize(12);
			        simSpeedSlider->minimum(0.001);
			        simSpeedSlider->step(0.001);
			        simSpeedSlider->value(0.001);
			        simSpeedSlider->callback((Fl_Callback*)simSpeedSliderCallback);
			        simSpeedSlider->align(FL_ALIGN_TOP_LEFT);      
			}
      			{	/* Perturbation Button */
				perturbationButton = new Fl_Check_Button(585, 565, 165, 15, "Perturbation");
        			perturbationButton->down_box(FL_DOWN_BOX);
			        perturbationButton->callback((Fl_Callback*)perturbationCallback, (void*)(numProductsSlider));
      			}
      			{	/* Hubs Button */
				hubsButton = new Fl_Check_Button(585, 590, 170, 15, "Hubs");
			        hubsButton->down_box(FL_DOWN_BOX);
			        hubsButton->callback((Fl_Callback*)hubsCallback, (void*)(&glf));
      			}
      			parametersGroup->end();
		}
		{	/* Menu */
			Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 925, 20, "View");
      			o->menu(menu_Visualizza);
		}
    		elanjaWindow->add(glf);
    		elanjaWindow->resizable(&glf);
    		elanjaWindow->end();
	}
	elanjaWindow->show(argc, argv);
	return Fl::run();
}
static int x; 
